
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.VBox vbox4;

	private global::Gtk.Entry txtPattern;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Entry txtFilename;

	private global::Gtk.Button btnLoad;

	private global::Gtk.VBox vbox2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TreeView tvNewValues;

	private global::Gtk.HBox hbox2;

	private global::Gtk.SpinButton sbtnNewValueIndex;

	private global::Gtk.Entry txtNewValue;

	private global::Gtk.Button btnAddAssignment;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button btnQuit;

	private global::Gtk.Button btnRename;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.txtPattern = new global::Gtk.Entry ();
		this.txtPattern.CanFocus = true;
		this.txtPattern.Name = "txtPattern";
		this.txtPattern.Text = global::Mono.Unix.Catalog.GetString ("^(\\w*)_(\\w*)_(\\w*)\\.vhdr$");
		this.txtPattern.IsEditable = true;
		this.txtPattern.InvisibleChar = '•';
		this.vbox4.Add (this.txtPattern);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.txtPattern]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.txtFilename = new global::Gtk.Entry ();
		this.txtFilename.CanFocus = true;
		this.txtFilename.Name = "txtFilename";
		this.txtFilename.IsEditable = false;
		this.txtFilename.InvisibleChar = '•';
		this.hbox3.Add (this.txtFilename);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.txtFilename]));
		w2.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnLoad = new global::Gtk.Button ();
		this.btnLoad.CanFocus = true;
		this.btnLoad.Name = "btnLoad";
		this.btnLoad.UseUnderline = true;
		this.btnLoad.Label = global::Mono.Unix.Catalog.GetString ("Durchsuchen...");
		this.hbox3.Add (this.btnLoad);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnLoad]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox4.Add (this.hbox3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox3]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add (this.vbox4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox4]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.tvNewValues = new global::Gtk.TreeView ();
		this.tvNewValues.CanFocus = true;
		this.tvNewValues.Name = "tvNewValues";
		this.GtkScrolledWindow1.Add (this.tvNewValues);
		this.vbox2.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow1]));
		w7.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.sbtnNewValueIndex = new global::Gtk.SpinButton (0, 100, 1);
		this.sbtnNewValueIndex.CanFocus = true;
		this.sbtnNewValueIndex.Name = "sbtnNewValueIndex";
		this.sbtnNewValueIndex.Adjustment.PageIncrement = 10;
		this.sbtnNewValueIndex.ClimbRate = 1;
		this.sbtnNewValueIndex.Numeric = true;
		this.hbox2.Add (this.sbtnNewValueIndex);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.sbtnNewValueIndex]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.txtNewValue = new global::Gtk.Entry ();
		this.txtNewValue.CanFocus = true;
		this.txtNewValue.Name = "txtNewValue";
		this.txtNewValue.IsEditable = true;
		this.txtNewValue.InvisibleChar = '•';
		this.hbox2.Add (this.txtNewValue);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.txtNewValue]));
		w9.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnAddAssignment = new global::Gtk.Button ();
		this.btnAddAssignment.CanFocus = true;
		this.btnAddAssignment.Name = "btnAddAssignment";
		this.btnAddAssignment.UseUnderline = true;
		this.btnAddAssignment.Label = global::Mono.Unix.Catalog.GetString ("Hinzufügen");
		this.hbox2.Add (this.btnAddAssignment);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnAddAssignment]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox2.Add (this.hbox2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w12.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnQuit = new global::Gtk.Button ();
		this.btnQuit.CanFocus = true;
		this.btnQuit.Name = "btnQuit";
		this.btnQuit.UseUnderline = true;
		this.btnQuit.Label = global::Mono.Unix.Catalog.GetString ("Beenden");
		this.hbox1.Add (this.btnQuit);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnQuit]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnRename = new global::Gtk.Button ();
		this.btnRename.CanFocus = true;
		this.btnRename.Name = "btnRename";
		this.btnRename.UseUnderline = true;
		this.btnRename.Label = global::Mono.Unix.Catalog.GetString ("Neu benennen");
		this.hbox1.Add (this.btnRename);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnRename]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
